name: link-force

services:
  postgres:
    container_name: link-force-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    ports:
      - 54321:5432
    networks:
      - link-force

  redis:
    container_name: link-force-redis
    image: redis/redis-stack-server:7.2.0-v10
    volumes:
      - ./docker/redis/redis.conf/:/redis-stack.conf
      - ./docker/redis/log:/var/log/redis
      - ./docker/redis/data/:/DATA
    ports:
      - 6385:6379
    networks:
      - link-force

  app:
    container_name: link-force-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:3000
    networks:
      - link-force

networks:
  link-force:
    driver: bridge
