name: link-force

services:
  mysql:
    image: mysql:8.0
    container_name: link-force-mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: link-force
      MYSQL_PASSWORD: link-force
      MYSQL_DATABASE: link-force
      MYSQL_ROOT_PASSWORD: link-force
    volumes:
      - ../.link-force/mysql/data:/var/lib/mysql
      - ../.link-force/mysql/log:/var/log
    ports:
      - 33067:3306
    restart: unless-stopped
    networks:
      - link-force

  redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: link-force-redis
    volumes:
      - ./docker/redis/redis.conf/:/redis-stack.conf
      - ../.link-force/redis/data/:/data
      - ../.link-force/redis/log:/var/log/redis
    ports:
      - 6385:6379
    restart: unless-stopped
    networks:
      - link-force

networks:
  link-force:
    driver: bridge
