name: Merge

on:
  workflow_run:
    workflows: ['Tagging']
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download tag info
        uses: actions/download-artifact@v4
        with:
          name: tag
          path: tag_info.txt

      - name: Read tag info
        id: read-tag-info
        run: |
          TAG=$(cat tag_info.txt)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Merge main to dev
        if: contains(steps.read-tag-info.outputs.tag, '-prod')
        run: |
          git config --global user.name "actions"
          git config --global user.email "actions@github.com"
          git checkout dev
          git merge main
          git push origin dev
