name: Tagging

on:
  workflow_run:
    workflows: ['Version']
    types:
      - completed

jobs:
  version:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]
        branch: [dev, main]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}

      - name: Tagging
        run: |
          version=$(cat package.json | grep '"version"' | awk -F '"' '{print $4}')
          tag=${version}-${matrix.branch}
          git tag $tag
          git push origin $tag
