name: Tagging

on:
  push:
    branches: ['main', 'dev']
    paths:
      - 'src/**'
      - 'package*.json'
      - 'tsconfig*.json'
      - 'nset-cli.json'
      - 'Dockerfile'
      - '.github/workflows/tagging.yaml'
      - '.github/workflows/deploy.yaml'

jobs:
  version:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "TAG_SUFFIX=dev" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "TAG_SUFFIX=prod" >> $GITHUB_ENV
          else
            echo "Invalid ref name. Branch name must be dev or main"
            exit 1
          fi

      - name: Set Version
        run: |
          if [ "${{ env.TAG_SUFFIX }}" == "prod" ]; then
            git config --global user.name "actions"
            git config --global user.email "actions@github.com"
            npm version patch
            git push origin ${{ github.ref_name }}
            git checkout dev
            git merge ${{ github.ref_name }}
            git push origin dev
          fi

      - name: Create Tag
        run: |
          version=$(cat package.json | grep '"version"' | awk -F '"' '{print $4}')
          commit_hash=$(git rev-parse --short HEAD)
          tag=${version}-${commit_hash}-${{ env.TAG_SUFFIX }}
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Push Tag
        run: |
          git tag -a ${{ env.TAG }} -m "Tagging ${{ env.TAG }}"
          git push origin ${{ env.TAG }}
